version: '3.8'
services:
  nodejs:
    container_name: nso-node-svc
    image: node:22
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && node index.js"
    networks:
      - bridge
  nginx:
    container_name: nso-nginx
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - nodejs
    restart: always
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
